### ISSUE TITLE
missing packages?

### ISSUE THREAD

**Issue by dfalster** [animaltraits/animaltraits.github.io#2]
Hi @JimMcL 

Nice work. I'm running the code in `R/analysis.R` to see if everything runs smoothly. We seem to be missing library call, as I get the following:

```
> source("standardisation/traits-config.R") # Defines traits_list and CONVERSIONS
Error in set_units(20, "J/ml") : could not find function "set_units"
```

Where is the function `set_units` coming from?

**Comment by JimMcL** [comment]
Suppressing messages on loading libraries meant that a failure to load a library was ignored. Messages are no longer suppressed.
